### ISSUE TITLE
Quest 6981

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#10]
Quest 6981 "The Glowing Shard" appears to be bugged. I ran two friends through Wailing Caverns last night and all three of us picked up the item to begin the quest. We all went to Ratchet as instructed to find a person who knows about the shard. The goblin by the taxi location was supposed to direct us to a female Tauren above Wailing Caverns, but he never activated. Going straight to the Tauren results in a silver question mark and being unable to turn in the quest.

**Comment by Ghurok** [comment]
The old mangos-zero script repository had this scripted but it isn't scripted here.

https://github.com/mangos-zero/scriptdev0/blob/develop/scripts/kalimdor/the_barrens.cpp#L169

Whether or not the old script is blizzlike, I don't know. The npc_text.ID 2013 that is used is correct at least but that's all I know.
