### ISSUE TITLE
Rexxar not walking

### ISSUE THREAD

**Issue by TobiasFriberg** [mangosArchives/databaseZero_Rel19#104]
Rexxar should be walking acress desolace. Anyone got information about the waypoints?

**Comment by Uccello** [comment]
"the warrior wandered a path from the Charred Vale in Stonetalon Mountains along the main road through Desolace and continued to the Twin Colossals in northern Feralas."   Source :  http://www.wowwiki.com/Rexxar

also near the top mentions this same path and a screenshot of him moving : http://wow.joystiq.com/2012/07/20/wow-archivist-the-most-painful-attunement-of-all/ 

not his full path but a video of him pathing not hanging out as he is now : https://www.youtube.com/watch?v=4pvkLsZa4uQ
 Hope this is a bit of help ( hoping to find something pinged on a map if i do I'll post with any updated info )

**Comment by danielsreichenbach** [comment]
Thanks a lot, good finds on those videos :thumbsup:

**Comment by Uccello** [comment]
Glad to help!

**Comment by billy1arm** [comment]
Fixed in Rel20
