### ISSUE TITLE
GM Island Mail box

### ISSUE THREAD

**Issue by MadMaxMangos** [mangosArchives/databaseZero_Rel19#108]
The mailbox on GM island can only be used by alliance. Can we find one that both factions can use?

**Comment by Elarose** [comment]
-- Sets gm island mailbox as unused neutral faction mailbox
UPDATE `gameobject` SET `id`=144570 WHERE `guid`=230922;

**Comment by billy1arm** [comment]
Awesome, we will get this into testing shortly

**Comment by billy1arm** [comment]
Added in Rel20
