### ISSUE TITLE
quests in Valley of Trials (Durotar)

### ISSUE THREAD

**Issue by kokeszko** [mangosArchives/databaseZero_Rel19#11]
almost all quests are marked there as both factions. shouldn't they be just marked as horde only?

**Comment by Salja** [comment]
can you pls post all entry of the quests

**Comment by kokeszko** [comment]
i'll paste just the ID of quests, they are marked as available for both factions but should be marked as for horde only:
6394, 5441, 4402, 804, 790, 789, 788, 787

**Comment by Salja** [comment]
thanks you

**Comment by Salja** [comment]
fixed close here
