### ISSUE TITLE
NPCs glitched at Tyr's Hand (screenshots)

### ISSUE THREAD

**Issue by MadMaxMangos** [mangosArchives/databaseZero_Rel19#111]
NPCs glitched at Tyr's Hand 

GUIDs in the chatbox of screenshots.

![wowscrnshot_080913_223751](https://f.cloud.github.com/assets/4533993/941143/64bcc478-013e-11e3-8ad2-e9a688d5fec4.jpg)
![wowscrnshot_080913_224109](https://f.cloud.github.com/assets/4533993/941144/65ea2aa2-013e-11e3-99da-0e4ab72d6e12.jpg)

**Comment by billy1arm** [comment]
This was fixed in a recent commit
