### ISSUE TITLE
Cannot enter Molten Core

### ISSUE THREAD

**Issue by weishan1981** [mangosArchives/databaseZero_Rel19#112]
I have completed quests before enter MC ,but can't enter MC,why?

**Comment by MadMaxMangos** [comment]
Confirmed. No option to teleport into Molten Core is offered after completing the quest.

NPC: Lothos Riftwalker
GUID: 3328

See attached screenshot below:
![wowscrnshot_081013_205741](https://f.cloud.github.com/assets/4533993/943165/a3275048-01f7-11e3-9737-5ce6df52c463.jpg)

Assigning issue to Ghurok.

**Comment by danielsreichenbach** [comment]
Lothos RIftwalker needs to be assigned gossip menu 5750, and the menu option requires a condition to be shown only with quest completed.

**Comment by TobiasFriberg** [comment]
You are suppose to jump out the window, thats the way its done in pre-TBC, right? Discussing it here http://us.battle.net/wow/en/forum/topic/9377057699?page=3 couldnt find a video about the real entrenc, but here is a video showing someone taking a shortcut. However, you can see that he is in the right spot when he teleports to MC. http://www.youtube.com/watch?v=TjVlSBZ3Hco about 35sec into the video.

<i>Edit</i>
More information:
https://github.com/FeenixServerProject/Old_1.12_Bugtracker/pull/2372

**Comment by danielsreichenbach** [comment]
You can only jump there, if you have the quest completed.

**Comment by TobiasFriberg** [comment]
That is correct, danielsreichenbach.

**Comment by danielsreichenbach** [comment]
Slight hint: the area trigger behind Lothos was properly set up, it just requires you to be in a raid group, and then it works. All that was missing was making the gossip menu available to characters having completed the quest.
