### ISSUE TITLE
Flight master Vesprystus pets wrong faction

### ISSUE THREAD

**Issue by MadMaxMangos** [mangosArchives/databaseZero_Rel19#116]
If this NPC is killed (I used .die for testing) she spawns pets that are hostile to the Darnassus guards.

I have linked the FP GUID and the faction templates of those as well, the pets that Vesprystus spawn should have their faction changed so they are not hostile to the Darnassus sentinel.

NPC: Vesprystus
GUID: 49938
Faction template: 14

Name: Enraged Hippogryph
Spawns from entry: 9527
Faction Template: 17

Name: Darnassus Sentinel
Faction template: 79

**Comment by danielsreichenbach** [comment]
This can only be faction template 80, not 79, as 79 is in the monster faction group.
