### ISSUE TITLE
Druid Spells

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#12]
All druid spells become available at level ten. The druid trainer lists them all as a level ten requirement. I will attempt to locate the issue (spell requirement orther issue) and post more information, but for now all I know is that if a druid was rich, it could have all of the spells at level ten.

**Comment by Salja** [comment]
yes you right the fix i have see in comming backport from one give me some time but fix come 100%

**Comment by cala** [comment]
This is a core issue, not a DB one. And as far as I remember, it only concerns feral spells.
Salja is right, it was fixed in mangos-one. I had it fixed also in old mangos-zero core before it was archived:
https://github.com/mangos-zero/server/commit/be46a2d299e84ecdd549c9b0538ce4622b53e4f4

**Comment by The-Great-Sephiroth** [comment]
Ah I figured it was DB since all of the spell data is stored there. Feel free to move this thread to server if you'd like.

**Comment by Salja** [comment]
thanks cala wehn im back next week i will look over this

**Comment by Salja** [comment]
must be fix in core [z2065]
