### ISSUE TITLE
Outdoor scenery can dismount you again...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#128]
I am using 2.0.8 and when entering Everlook I was dismounted. I have also discovered a few other locations that do this also.

**Comment by danielsreichenbach** [comment]
This is not a database issue. It would be a server issue.

If you could please recreate this issue on the server issue tracker, and add the locations you have found to be dismounting you instead of leaving you mounted, that would be great.
