### ISSUE TITLE
NPC: Arch Druid Fandral Staghelm

### ISSUE THREAD

**Issue by MadMaxMangos** [mangosArchives/databaseZero_Rel19#135]
NPC: Arch Druid Fandral Staghelm
Entry: 3516 / GUID: 46903
Location: Cenarion Enclave, Darnassus

This NPC is missing the following: Abilities, Aggro/kill emote/messages, Summoning of pet treeants, using the entangling roots

This NPC is "supposed" to be the hardest alliance leader to kill.

**Comment by kokeszko** [comment]
already in UPdate 210_updatepack.sql (lines 116-130)

**Comment by Evildead666** [comment]
sorry forgot to close this issue
