### ISSUE TITLE
quest 770 (The Demon Scarred Cloak) is bugged

### ISSUE THREAD

**Issue by kokeszko** [mangosArchives/databaseZero_Rel19#139]
quest starts after using Demon Scarred Cloak (item 4854).
upon finish, player gets reward but Cloak is not removed from inventory.

**Comment by Uccello** [comment]
http://www.wowhead.com/quest=770

## 

By Scandinavian (322 – 3) on 2010/06/11 (Patch 3.3.3) Report  
The item does not get automatically removed from your inventory upon completion of the quest.
This was changed closer to cata : 

1

## 

By Novawolf (10,633 – 2·10·86) on 2011/04/01 (Patch 4.0.6)  Report  
At time of posting, the cloak that provides the quest is removed once you turn in this quest.

I was surprised and disappointed after popping out of my Cat-form after a long session of questing to realize I was now cloak-less.

Real shame, I love the dark-colored long capes.

As of patch 4.3 the cloak is no longer wearable, it is now just a quest item in your inventory.

**Comment by kokeszko** [comment]
didn't noticed that and didnt even try to wear it. closing then as a false report
