### ISSUE TITLE
Quest "Winterfall Activity" rewards too much exp...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#14]
The quest "Winterfall Activity" rewarded me 90,000 exp when I turned it in. I believe it should have been 9,000 exp instead. It gave me half a level or close to it at level 58.

**Comment by Salja** [comment]
quest entry ? on wowhead i found only from cata

**Comment by The-Great-Sephiroth** [comment]
The entry is 8464 in my database.

**Comment by Salja** [comment]
thanks i will check

**Comment by Ghurok** [comment]
quest_template.RewMoneyMaxLevel is the column that needs to be altered. We still need the correct XP reward from a reliable source however.

**Comment by Evildead666** [comment]
Big changes to winterfall quests have been done in 1.9, but i haven´t found out yet what exactly have changed

**Comment by danielsreichenbach** [comment]
This requires a bit of research, and thus will be scheduled for release 2.0.8, since it can not be resolved for 2.0.7.

**Comment by danielsreichenbach** [comment]
I have just checked this in a BradyGames book for patch 1.12. According to their tables, the correct XP for this quest would be 6200.

**Comment by Ghurok** [comment]
It was 6200 in patch 1.9 as well. Now we need to figure out how the XP reward is 6200 but the money reward at Lvl. 60 is 3G 72S.
