### ISSUE TITLE
quest 6361 (A Bundle of Hides) is partially buged

### ISSUE THREAD

**Issue by kokeszko** [mangosArchives/databaseZero_Rel19#140]
Wind Rider Master Devrak ends this quest and he should have a question mark above him. He doesn't have it. You need to talk to him, then appears an option to end his quest.

**Comment by Uccello** [comment]
This works perfectly fine.
1. Be sure you are a Tauren as it is a tauren only quest ( I tried it on several horde toons and didnt get a ?)
2. If you have not learnt the flight point the ? will not appear until after you have done that and then speak to him
3. If you  have learnt the flight point already the ? does appear over his head
Screenshot : 

http://imageshack.us/photo/my-images/30/z99m.jpg/

**Comment by kokeszko** [comment]
if you say so, then ok. but as i remember, i've talked to wind master first, took fly point and after it took that quest. hence this report.

**Comment by kokeszko** [comment]
i'm not able to reproduce this bug. closing it
