### ISSUE TITLE
QUEST 606 ERROR!

### ISSUE THREAD

**Issue by tsui110** [mangosArchives/databaseZero_Rel19#146]
The quest 606!
If accepting the quest 606 will crash the server!This bug is very fatal!

**Comment by Salja** [comment]
Chrashlog ?

**Comment by tsui110** [comment]
sry.my worldlogfile is disable.if youneed the log i  can offer it！

**Comment by Evildead666** [comment]
can you add the logfile here.
Tested today and nothing happened

**Comment by billy1arm** [comment]
@tsui110 - Can you confirm this is still happening

**Comment by tsui110** [comment]
@billy1arm sry!Buddy! there is something wrong with os!

**Comment by jaxx56** [comment]
Doesn't sound like it would be a OS issue, but it's always possible. If it occurs again, please reopen this.
