### ISSUE TITLE
got database errors then starting mangosd [zero]

### ISSUE THREAD

**Issue by kris914g** [mangosArchives/databaseZero_Rel19#147]
hey i have newly compiled mangos zero complely and i open realmd without any errors but then i open mangosd i got some mysql errors so i have maked a video so you can see all the details where you can see all my errors then im startig mangosd you can se it here and remember to use full screen so you can se the words in the terminal i hope any of you can help me 

p.s im using ubuntu but i think is the mysql databases there is wrong. 

enjoy the movie ;)

video: https://www.dropbox.com/s/2ktjsc9ptuf2sgy/error%20fix%20help.mp4

**Comment by Evildead666** [comment]
Your DB is fine.
The errors are known and most of them are already fixed and will be gone with the next DB release.
The large bunch of creatureAI errors can be ignored for now, these scripts are still working fine.

A error list can be found in the .log files in the server directory.

**Comment by kris914g** [comment]
okay but what about the updates i  cant update the database i got a error ther say you must install 123123_mangos_example.sql before or is it just to install the core patch?  =    210_corepatch_mangos.sql and 210_updatepack.sql or is there more???

**Comment by kris914g** [comment]
and i cant upload your develop updates then i got this error then trying to upload Evildead666_Big Backport.sql

INSERT INTO  `db_script_string` 
VALUES ( 2000000016,  'Ok, good luck friend. Thanks for the help.', NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , 0, 0, 0, 0, NULL ) ;

MySQL returnerede: Dokumentation

#1062 - Duplicate entry '2000000016' for key 1

**Comment by AntzMangos** [comment]
if you change INSERT INTO to REPLACE INTO, that will overwrite what you currently have in the database

**Comment by kris914g** [comment]
where can i do that?

**Comment by kris914g** [comment]
oh now i see should i do that in the .sql file but

should i also use the sql files there are placed in C:\Users\kristoffer\Desktop\server-master\sql\updates ?? or just 210_corepatch_mangos.sql and 210_updatepack.sql or is there more??? and what about the realmd and characters and script server??
