### ISSUE TITLE
Molten Core Bug!

### ISSUE THREAD

**Issue by tsui110** [mangosArchives/databaseZero_Rel19#148]
The quest id 7487 is done!
After I talked with the teleNPC,I will enter the molten core!
But after talking and triggers active,I am still here!
Only with  the gm mode on,I can enter the molten core!
Is there anyone has the same error?

**Comment by Evildead666** [comment]
Did you finish the quest by accepting it or did you add it with a gm command?
7487 is the old version of the quest which have been removed in 1.12 and replaced by 7848.
Finishing 7848 should grant you acces to the core.

**Comment by tsui110** [comment]
@Evildead666  thank you very much!dude!
