### ISSUE TITLE
The Duels -Pvp bug

### ISSUE THREAD

**Issue by Nexams** [mangosArchives/databaseZero_Rel19#149]
When You duel /pvp with any player You see them going all around although they are in the same place .
Its a major Bug and destroys the the game pvp part which is a major part or lets say its like 30% of wow Expirence

**Comment by Meltie2013** [comment]
Looks like a sync issue more then likely.. I can look around and see what I can do.

**Comment by billy1arm** [comment]
This has been resolved in Rel20
