### ISSUE TITLE
Loot while In Group is Bugged /All types of loot in group

### ISSUE THREAD

**Issue by Nexams** [mangosArchives/databaseZero_Rel19#150]
So when you are in a party and Doing Quests ,and you kill lets say a mob that drop a quest item like a  "head " Only one can loot and so the players do the quest they  have to wait until mob respawn or Ask gm to do .respawn ,

and while looting only one can loot if some one does shit-loot the whole drop is gone

**Comment by Uccello** [comment]
This has already been reported in other bug reports
