### ISSUE TITLE
Quest 8460 bugged...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#22]
The quest "Timbermaw Ally" works except it grants 63,000exp instead of what I assume should be 6,300exp. I just completed it using the build I built tonight from the repository, so this is a current stable build, not testing.

**Comment by danielsreichenbach** [comment]
This requires a bit of research, and thus will be scheduled for release 2.0.8, since it can not be resolved for 2.0.7.
