### ISSUE TITLE
Creature_Template 

### ISSUE THREAD

**Issue by e46ad** [mangosArchives/databaseZero_Rel19#225]
Creature_Template is broken for Rel20 every single creature/mob in the world has incorrect damage values and speed values, Makes it impossible to farm instances, Elite quests or world bosses, This issue needs addressing urgently as it's gaming breaking and make's the over all experience of the game worthless.

**Comment by e46ad** [comment]
You can mob tag the whole starting zone on Rel 20 DB using a healer and X it doesn't matter what class you are you can aggro 20-30 starter zone mob's that all hit you for 1 a Healer at level 1 can out heal this damage very easily. I have tested almost every single Instance and Raid in the game to this point and every elite is One shoting me almost it doesn't matter if there level 20-35-50-60 etc etc   I die almost instantly from the mob's using a fully geared Nax with my Hp .mod hp 6k 6k they kill me within 2-3 hits,

https://www.youtube.com/watch?v=xmqrvVdBbo4

https://www.youtube.com/watch?v=UW69yk67h5M

https://www.youtube.com/watch?v=pTxTbZ-FIcM

3 simple videos that show how outrages the damage is with a fully geared character with gear that most people would never earn playing, The reason i don't get one shot instantly in the videos is due to me modding my hp to 5k every second with a macro. 

I know this is not a fault or bug on my end as i have run previous versions fine, Plus i have being talking to a Dev about this Matter you can find the whole tread here,

https://www.getmangos.eu/general-help-amp-support/10305-mangos-zero-creature-damage-issue-help.html

This should be a matter of urgency for the mangos team to get a fix out for this ASAP, The competitors out there Don't have this issue I'm not going to name them but this is seriously game breaking for the DB and progress of mangos.

I hope this helped and i look forward to hearing from a Dev soon regarding this issue.

**Comment by billy1arm** [comment]
Since this is being dealt with in the thread, i'll close this as it's a duplicate.
