### ISSUE TITLE
Spell cast stays after interruption

### ISSUE THREAD

**Issue by ghost** [mangosArchives/databaseZero_Rel19#24]
As the title says :)

![WoWScrnShot_020813_211126](https://f.cloud.github.com/assets/3449551/140736/414f55ce-722c-11e2-9ef6-cf73a60768dc.jpg)

**Comment by Salja** [comment]
you found a fix in the server / testing branch pls testing and give here feedback

PS: its core issue
https://github.com/mangoszero/server/commit/d895a09b79e88fe42e8e369f22a234213fd1e154

**Comment by ghost** [comment]
oh right my bad, should have posted @server

anyway I just compile a fresh version of the core and that didnt seem to fix it : / dunno if Im doing something wrong.
might not have done everything correct so will check when I get back home.

**Comment by Salja** [comment]
you need to checkout the testing branch i have tested for me works fine

**Comment by ghost** [comment]
probably a stupid question but how do I get the git URL for specific branches? I saw that you merged master with testing but the usual git URL only downloads the master one and doesnt show me the URL for the testing branch.

**Comment by Salja** [comment]
wehn you have clone the repo than "git checkout testing" than compile and test and pls feedback here

**Comment by ghost** [comment]
alright got it working, turtoiseGIT didnt recognize the testing branch so had to add it manually. No more glow when spell is interrupted :) ur such a beast salja, keep up the good work it's much appreciated :)

**Comment by Salja** [comment]
thanks for feedback you tested the AP Cat Bug https://github.com/mangoszero/database/issues/25 ?

**Comment by ghost** [comment]
Yepp bear and cat form increases AP properly but cat form does still not reward that little extra agility, Im not sure how much agility it should increase exactly but on the spell it reads: "increasing melee attack power by 40 plus agility". Spoke to my mate just to clarify that you actually did get extra agility in cat form and he agreed that that was the case.

He was pretty sure cat form should increase crit and dodge aswell which in other words mean that it should increase agility. Im not 100000% sure but I got a second opinion on it so should be worth taking a look at. :)

**Comment by The-Great-Sephiroth** [comment]
What that means is that your attack power is increased by 40 plus whatever your agility is. In other words if you have 100 agility your AP should go up by 140. There is no agility increase.
