### ISSUE TITLE
Tauren NPC sizes...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#33]
Many Tauren NPCs are as small as my undead. Just check out Cairne Bloodhoof! His bodyguards are also tiny. My Tauren shaman currently towers over his own leader. I am guessing that the new database has all model sizes set to 1.0?

_UPDATE_

It appears as though all Tauren in Thunder Bluff are super small. A simple fix for this would be an SQL query to adjust the scale to the correct size if the NPC is of the Tauren race. If somebody will tell me what the correct scale is, I will write the query.

**Comment by Salja** [comment]
you can check this old database and update with this i think thats worked

**Comment by The-Great-Sephiroth** [comment]
I will do this later. I am currently sick and stopped up, as well as running a temperature and light-headed. Not in any condition to think right now. I will have it finished by the end of the week.

**Comment by The-Great-Sephiroth** [comment]
I felt a bit better today so I started this and even the old database has missing or erroneous data. I am going through and manually updating my database using MySQL Workbench and will release an update SQL file when done.

**Comment by Salja** [comment]
musz be fixed here https://github.com/mangoszero/database/commit/61d58db766c5b209737b91286c623ae667f83835

**Comment by The-Great-Sephiroth** [comment]
I don't see Cairne Bloodhoof being set correctly there. In fact I see the Tauren being set to 1.35 instead of 1.4 for some reason. Once you update the update files  so I can update to 2.0.4, I will check it out, but everything I found told me that Tauren are 1.40, not 1.35. I can check by placing my Tauren next to one though.

**Comment by Salja** [comment]
i have used the old scale datas from old zero db repo for the moment i self not sure what is right some ppls say 1.3 some say 1.4 and some say 1.35 xd

and 2.0.4 is released sice yesterday

**Comment by The-Great-Sephiroth** [comment]
1.30 is too small. You can confirm by placing a player Tauren directly in front of an NPC Tauren and adjusting the NPC size. Honor Guards are good for this since they do not move. The correct size should be 1.40. At 1.40 the Honor Guards are exactly as tall and bulky as my player Tauren. 1.35 is a hair smaller, but it may pass if people are not paying attention. Also, Cairne Bloodhoof was roughly 2.00 scale. He towered over other Tauren and was **NOT** the same size as the guards who protect him.
