### ISSUE TITLE
[quest] Cluck! (3861)

### ISSUE THREAD

**Issue by ghost** [mangosArchives/databaseZero_Rel19#42]
In Westfall, the quest Cluck! (3861) requires Special Chicken Feed (11109) but the quest is not completable. The chicken becomes friendly after you emote /chicken 50 times, but even if you buy chicken feed or use ".additem 11109" it still does not meet the requirement.

**Comment by The-Great-Sephiroth** [comment]
As I said on the forum, use ".quest complete 3861" as opposed to adding the item to the inventory. I did this quest and it works. I will try again tonight since it has been a while.

**Comment by The-Great-Sephiroth** [comment]
Alright I just went and tried it with a fresh character and it is indeed bugged. In fact if you try ".quest complete 3861" it claims that the quest is not found. However, doing ".lookup quest cluck" reports the quest as the proper ID and all. Also, adding the special grain or buying it does not allow it to be completed.

**Comment by danielsreichenbach** [comment]
This requires a bit of research, and thus will be scheduled for release 2.0.8, since it can not be resolved for 2.0.7.

**Comment by The-Great-Sephiroth** [comment]
This is still bugged. I just tried it. The item that the farmer sells is 11109. I also spawned the same item by using additem and shift-clicking the feed listed in the quest dialogue window. Also item 11109. Basically, you have the right item but I am assuming that the quest is triggered with the wrong item ID.

**Comment by The-Great-Sephiroth** [comment]
I am not sure how the database sets up quests, but I do see the item ID referenced in the database entry for the quest. I also tried cheering at the chicken but nothing made the "Complete" button come to life.

**Comment by danielsreichenbach** [comment]
This does require support in the script library. Using the emote on the chicken had a random chance which could proc on the first try, but also take 20 tries to work.

**Comment by The-Great-Sephiroth** [comment]
Well the initial script is perfect. If you do "/chicken" fifty times, the chicken shows up with the quest marker. However, I have a macro for "/cheer" which does it ten times with each key press. I did it over a hundred times and the chicken never acknowledged it. I'd say it has about a 0% chance of working. Still, if this is a script issue, a report should be opened there.

**Comment by danielsreichenbach** [comment]
Issue is now in mangoszero/scripts#12 and thus closed. We will have to fix the script here.
