### ISSUE TITLE
[quest] Watcher Callahan (236)

### ISSUE THREAD

**Issue by ghost** [mangosArchives/databaseZero_Rel19#43]
Quest displays error in the quest log.
![watchercallahan](https://f.cloud.github.com/assets/3746854/238503/2eec4f3a-883a-11e2-8b62-c7f5c4583a5e.PNG)

**Comment by The-Great-Sephiroth** [comment]
Call me blind, but where is the error? The description is 100% correct, so I am not sure what the problem is.

OH I see it. It says "Missing header" instead of the quest title.

**Comment by Salja** [comment]
the problem is on wowhead and other i cant not more found this quest =(

**Comment by Sinoxan** [comment]
We've tried researching this before but there is very little information on it, we came to the conclusion that it was part of a quest chain that was removed some time after the end of the beta but the NPC was left in with nothing to do.

**Comment by The-Great-Sephiroth** [comment]
Are you sure that this was removed? I could swear I went to Callahan for a quest.

Wasn't this NPC added in 1.10 or 1.11? I found this being discussed on another forum and they claim he was added in 1.11. I believe that he was there before then. However, the quest was removed in 2.4.3, so it was there during 1.12.

http://pretbc.com/viewtopic.php?pid=9905#p9905

**Comment by Salja** [comment]
i will check my books i have here 1.12.1 books with all quests etc

**Comment by Salja** [comment]
in my book i can found this quest so its not delete in classic my book is 1.12.1 the header info is fixed

**Comment by The-Great-Sephiroth** [comment]
Cool, I thought that I remembered this quest!
