### ISSUE TITLE
Outdoor models cause dismount...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#49]
Certain outdoor models cause players to dismount, such as the bridges in STV or the entrance to Everlook.

**Comment by Elarose** [comment]
https://github.com/mangoszero/server/issues/44  Try that until a better solution. All dismounting -dire maul entry/stv bridges etc- are from extracting from old patches.

**Comment by lfxgroove** [comment]
Closing this as it seems the problem was old binaries as described here https://github.com/mangoszero/server/issues/44
