### ISSUE TITLE
The rogue talent "Relentless Strikes" is bugged...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#51]
The rogue talent "Relentless Strikes" is supposed to have a 20% chance to restore 25 energy per combo point on the target. This is broken. Instead my combat log says I gain 5 energy from a spell called "Head Rush".

**Comment by Ghurok** [comment]
For devs: The spell that gives you 25 energy has the ID 14181 I believe.

**Comment by danielsreichenbach** [comment]
This requires a bit of research, and thus will be scheduled for release 2.0.8, since it can not be resolved for 2.0.7.

**Comment by danielsreichenbach** [comment]
This is a server issue and has been moved to [this server issue](https://github.com/mangoszero/server/issues/117).
