### ISSUE TITLE
The Rogue skill "Sprint" is broken...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#53]
At least, rank 2 is. I cast sprint and nothing happens except for sprint going on cooldown. Rank 1 appears to work.

**Comment by Ghurok** [comment]
It works for me.

By the way there seems to be a lot of issues you have but that work for me and Salja for some reason.

**Comment by The-Great-Sephiroth** [comment]
Rank 3 doe snot work on my end. Rank 1 does. As far as why this does not work, I believe a lot of updates are left out of the update scripts. The reason that I believe this is because I will start with a database and then perform updates instead of full installs every time. Eventually things like this come to pass. I will then delete my world database and use the full install database script and things work again. This cycle has happened multiple times this past year, leading me to believe that the updates don't contain every single update that is in the full database script.

I will drop my database and do a full install and see if it remedies the situation. My other theory is the broken ACE handling right now. I only run Linux dedicated servers, not Windows. Even my domain controllers are Debian Linux servers using SAMBA4 to host a Server 2008 R2 functional level domain including group policies, deployed software, and various services such as print servers. ACE is broken in the Linux build process, so maybe that is affecting me.

Still, let me do a fresh world database and if that fixes my issue then it will prove that updates are being left out of the updates for the database. If it does not, then I do not have a clue since I will be running the latest stable code and database.

**Comment by The-Great-Sephiroth** [comment]
Alright, fresh database version 2.0.5 with the server version 2302. Sprint rank 3 is still broken. The spell ID is 11305. The character is an undead rogue. I would be more than happy to create accounts for you if you want to see this in person. I can also record this and upload it to YouTube. Either way, it shows the animation and plays the sound, but I do not get the sprint buff that actually increases speed.

**Comment by Salja** [comment]
fixed https://github.com/mangoszero/server/commit/1781ac3c1e2219eaa0ce42663bc7e85b319ff482
