### ISSUE TITLE
Thrall is weak!

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#57]
Thrall currently has 40,000 HP. Isn't this supposed to be 400,000? I mean the king of Stormwind has over 525,000!

**Comment by jaxx56** [comment]
http://db.valkyrie-wow.com/?npc=4949 ?

**Comment by The-Great-Sephiroth** [comment]
That does not seem correct. I seem to remember him having at least 400k before. Maybe he had a range like 360k-400k? Either way, 40k is WAY too low. I set Thrall to have 400k on my server for the time being. Remember, Valkyrie is based on MaNGOS (at least I am fairly sure it is) so they may have just changed it from 40k to what they felt was correct.

**Comment by jaxx56** [comment]
Yeah i agree.. But if my memory serves me right.. i my self don't recall Thrall having 40k HP back in vanilla.

**Comment by The-Great-Sephiroth** [comment]
He didn't. At 40k a 60 paladin and 60 lock just owned him. I remember 40-man raids wiping on him so that cannot be right.

**Comment by ghost** [comment]
Incorrect expansion values on the creatures in the database most likely. All the creatures might need a recheck on expansion values to correct the health values. I can't say for sure, cause I don't know much with this expansion.

**Comment by Titarion** [comment]
All City bosses need to have their values checked.

**Comment by danielsreichenbach** [comment]
I will be checking a few old data sources for the proper health values. A few books by Bradygames from 2005 and 2006 mention health values for creatures, and supposedly these have been given to Bradygames by Blizzard.

**Comment by danielsreichenbach** [comment]
Found the faction leader in a BradyGames book.

### Thrall
- Health points: 1055700
- Mana points: 50805
- Damage: 1830 - 2422
- Armor: 6193

### Update

According to the books imprint, it is for 2.0.1, so this may already be the updates values for TBC.

Currently we do have different health values for all faction leaders, which does seem outright bogus, too. I would have assume their stats to be in the same range to avoid claims of faction preference.

**Comment by danielsreichenbach** [comment]
Due to the requirement for further research, a fix will be postponed to version 2.0.8.

**Comment by MadMaxMangos** [comment]
Thrall HP here - http://www.wowwiki.com/Talk:Thrall#Thrall.27s_HP
