### ISSUE TITLE
Can't enter Black Rock Depths while under level 60

### ISSUE THREAD

**Issue by ghost** [mangosArchives/databaseZero_Rel19#58]
Well you should be able to enter Black Rock Depths at level 48, seems to be a database error, I've deleted the following entry from areatrigger_teleport ->  " id   | name                                         | required_level | required_item | required_item2 | required_quest_done | target_map | target_position_x | target_position_y | target_position_z | target_orientation
2890 | Molten Core Entrance, Inside                 |             60 |             0 |              0 |                   0 |        230 |           1115.35 |           -457.35 |            -102.7 |                0.5 "

that seemed to have fixed it.

If you don't delete it, you get the message that "you have to level 60 to enter this instance" in an infinite loop even though you aren't even trying to enter anymore.

**Comment by Titarion** [comment]
Fixed. Bug was caused by the MC to BRD trigger not being set to level 48.
