### ISSUE TITLE
[mmaps] Dire Maul

### ISSUE THREAD

**Issue by ghost** [mangosArchives/databaseZero_Rel19#60]
the movment maps doest seem too friendly with dire maul. With mmaps enabled mobs jump in the air, evade as soon as you aggro them and it's just generally chaos.

I fear the mmaps needs to be fixed in order for the instance to be doable. Mobs (especially in the sector above Tendris Warpwood) tend to fall through the ground as they die, or just glitch trough the ground when you pull them.

**Comment by Salja** [comment]
you can disable the map by config option only the map i can say yes this map have a problem atm

**Comment by ghost** [comment]
I've done that but it's still really glitchy :(

**Comment by Elarose** [comment]
https://github.com/mangoszero/server/issues/44 Until a better solution is found, try this. Dire maul works 100% mmaps enabled. =)

**Comment by lfxgroove** [comment]
Closing this as it seems old binaries were the problem described in https://github.com/mangoszero/server/issues/44
