### ISSUE TITLE
quest 4941 is buged

### ISSUE THREAD

**Issue by weishan1981** [mangosArchives/databaseZero_Rel19#61]
Speak with Eitrigg in Orgrimmar. When you have discussed matters with Eitrigg, you have no choice,simplely you can't trigger the choice

sorry for my english!

**Comment by billy1arm** [comment]
The main getmangos.com website / forums are currently under a sustained ddos
attack, please visit the backup forum at http://www.getmangos.freeforums.org

**Comment by Ghurok** [comment]
Fixed in commit e7a0c8f
