### ISSUE TITLE
Quest 365 - picking up a pumpkin doesn't show what's happening in the spell bar

### ISSUE THREAD

**Issue by lfxgroove** [mangosArchives/databaseZero_Rel19#67]
When you pick up a pumpkin it doesn't show anything in the spell casting bar, there should probably be some text there, such as opening?

**Comment by danielsreichenbach** [comment]
Investigating if I can find screenshots or videos related to this.

**Comment by Ghurok** [comment]
They show "Opening" for me.

Screenshot: http://puu.sh/3JLeM.jpg

In terms of proof I could only find this video from 2009: http://www.youtube.com/watch?feature=player_detailpage&v=5CjYDkAUPy0#t=25s

**Comment by lfxgroove** [comment]
Ah, my bad then, sorry bout that
