### ISSUE TITLE
Spirit Healer Speech bubble

### ISSUE THREAD

**Issue by MadMaxMangos** [mangosArchives/databaseZero_Rel19#81]
![wowscrnshot_080313_113205](https://f.cloud.github.com/assets/4533993/905441/0ff521f8-fc28-11e2-902f-0dc68911327b.jpg)
With GM mode on all spirit healers have a speech bubble but no speech! The speech bubble should be removed.

**Comment by danielsreichenbach** [comment]
The speech bubble is still shown to indicate the availability of gossip, even in GM mode.
