### ISSUE TITLE
Dire maul instance doors do not close

### ISSUE THREAD

**Issue by MadMaxMangos** [mangosArchives/databaseZero_Rel19#83]
The doors that require the Crescent Key at die maul sometimes do not close after being opened either with the key or from the inside by the torch.
If they do close its can be after 5 minutes which is to long.

Location: Dire Maul

Object: Door(North)
## ID: 177192 / GUID: 49948

Object: Torch(north)
(This should reset when the door closes).
ID: 179510 / GUID: 49962

Object: Door(1 West)
## ID: 177189 / GUID: 49945

Object: Torch(West 1)
(This should reset when the door closes).
ID: 179508 / GUID: 49960

Object: Door(2 West)
## ID: 177188 / GUID: 49943

Object: Torch(West 2)
(This should reset when the door closes).
ID: 17950 / GUID: 49958

**Comment by Elarose** [comment]
-- Update doors to close in 5 seconds and torch return state 5 seconds
-- GAMEOBJECT_TYPE_DOOR = 0
-- data0: startOpen (Boolean flag)
-- data1: open (LockId from Lock.dbc)
-- data2: autoClose (65536 \* seconds) (e.g. open after 5min = 19660800)
UPDATE `gameobject_template` SET `data2`= 327680 WHERE `entry` IN (177188,177189,177192,177198,179507,179508,179510,179513);
