### ISSUE TITLE
UBRS - missing npc's

### ISSUE THREAD

**Issue by stan84** [mangosArchives/databaseZero_Rel19#84]
UBRS the furnance 
- a group of npc should patrol area between beast chamber and bridge hordeman city
- missing at least 4 groups in Spire Throne:
  1st standing opposite of enterance 2 orcs, 3 drakes
  2nd patroling the chamber 2orc, 3 drakes
  3rd standing at corner left from enterance
  4th standing far corner of chamber.  
- missing orcs at enterance to BRS, there should be few orcs camping at left and right side,
- missing grups at small rooms in Hall of Blackhand

http://www.youtube.com/watch?v=asKYQoMPbks since 6:15 shows what kind of mob is in each pack

**Comment by danielsreichenbach** [comment]
Added in dd135aa5255bcc8aae2e318374521917e1321158
