### ISSUE TITLE
Stelthed mobs not showing?

### ISSUE THREAD

**Issue by TobiasFriberg** [mangosArchives/databaseZero_Rel19#85]
Stelthed mobs are not vissible untill they are in combat, unless you are GM. They should be visible when you are within X-yards to target them. Don't know if this is a invisibility detection problem but its verry confusing. Example in Tanaris: Westewander Rogue. Not even in levels above 45 could i see them.

**Comment by Ghurok** [comment]
I've just tested this. It is working as it should as far as I can tell. You CAN see stealthed NPCs before they are in combat if you're within X-yards range. I'm closing this issue. However if you notice any problems with the actual range before they're visible, please create a new issue. Thank you. :)

![](https://f.cloud.github.com/assets/1886657/916985/377e2e16-fe9b-11e2-992c-848cbf95eba3.jpg)

GM mode is off.

**Comment by TobiasFriberg** [comment]
It seems about the right range to see them, I could not see them tho, neither could my friend. I guess I have to do some more testing on these mobs. What happens when you lower your level to 45-50? Do you still see them?

**Comment by danielsreichenbach** [comment]
If your level is lower you will see them from shorter range than with equal or higher range.

**Comment by TobiasFriberg** [comment]
I just tried with level 45 and its way to hard, I can only see them when i walk into them, and they are from range 40-45. I should be able to detect them a bit more easy. when in level 45. I tried level 55 and i was able to see them from longer range, not verry far, but a decent range. I think it should be raised a bit tho.
