### ISSUE TITLE
Quest item drops

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [mangosArchives/databaseZero_Rel19#9]
Quest item drops that do not start quests should only drop if a player is on the associated quest. A good example is Arnak Grimtotem in Thousand Needles. You can kill him both before and after doing his bounty quest and he still drops the quest item (his hoof) though it should only drop during the quest.

**Comment by danielsreichenbach** [comment]
This requires a bit of research, and thus will be scheduled for release 2.0.8, since it can not be resolved for 2.0.7.

**Comment by danielsreichenbach** [comment]
The loot template is lacking a condition to restrict it to characters having taken the quest.

The quest is [Wanted - Arnak Grimtotem](http://www.wowhead.com/quest=5147) and the item to be looted is [Arnak's Hoof](http://www.wowhead.com/item=12884).
